@walletHost = http://localhost:8080
@paymentHost = http://localhost:8081

### Créer un portefeuille
POST {{walletHost}}/api/wallets
Content-Type: application/json

{
  "phoneNumber": "+221779998877",
  "email": "testclient@gmail.com",
  "initialBalance": 25000,
  "code": "WLT-TEST001",
  "currency": "XOF"
}

### Lister les portefeuilles avec pagination
GET {{walletHost}}/api/wallets?page=0&size=10

### Consulter un portefeuille par numéro de téléphone
GET {{walletHost}}/api/wallets/+221779998877
### Test wallet introuvable
GET {{walletHost}}/api/wallets/+221700000000